---
title: "Coronavirus (COVID-19) Dashboard with {flexdashboard} package (part I)"
author: "Rubén F. Bustillo"
date: 2020-03-05
categories: ["R"]
tags: ["coronavirus", "flexdashboard"]

---


```{r setup, include=FALSE}

knitr::opts_chunk$set(collapse = TRUE)

```

**Re**

This post presents a dashboard with information on coronavirus. The {coronavirus} package is available on CRAN and comes from The [John Hopkins University Center for Systems Science and Engineering](https://hub.jhu.edu/2020/01/23/coronavirus-outbreak-mapping-tool-649-em1-art1-dtd-health/). 

\

# Coronavirus Dashboard

\

In this post I present a **dashboard with information about the evolution of coronavirus (COVID-19)**. I use the coronavirus dataset from the {coronavirus} package, available on CRAN. The information comes from The [John Hopkins University Center for Systems Science and Engineering](https://hub.jhu.edu/2020/01/23/coronavirus-outbreak-mapping-tool-649-em1-art1-dtd-health/) (CSSE). The coronavirus dataset is updated daily by [Rami_Krispin](https://twitter.com/Rami_Krispin) and the information is available at [his github account](https://ramikrispin.github.io/coronavirus/). 

\

To create the dashboard I will use the {flexdashboard} package. I take this opportunity to thank Rami Krispin for sharing his work and code with the rstat community. His dashboard on coronavirus has helped me tremendously to improve my knowledge of the {flexdashboard} package.

\

The dashboard on coronavirus is deployed in rpubs.com:

\

[Link to the dashboard](https://rpubs.com/rubenfbc/coronavirus)